### ISSUE TITLE
URL-Адреса

### ISSUE THREAD

**Issue by AllueXD** [SaltOnAStick/mistage-roadmap-game#1]
Не меняются URL-Адреса при переходе между страницами. 
Проблема возникает при переходе с любой страницы на другую. Так, при переходе со страницы "Введение" на "Обзор" URL-адрес остаётся тем-же "https://mistagedev.github.io/pages/page.html".
Страница "Введение"
![изображение](https://user-images.githubusercontent.com/53126226/134181723-489aa5b7-d50e-445a-8721-b83e6f38635e.png)
Страница "Обзор"
![изображение](https://user-images.githubusercontent.com/53126226/134181798-bb4c2299-d25c-4bd4-ab7a-078186210978.png)

**Comment by Nebulorion** [comment]
Было выявлено, что проблема возникает из-за скрипта подгрузки страниц client-side-include.js.
Для решения этой проблемы будет переписан  скрипт подгрузки страниц так, чтобы контент веб-страницы собирался относительно страницы с контентом, а не области с навигационным меню.
![image](https://user-images.githubusercontent.com/53240042/134183944-b3e7da1f-3e82-4095-8c80-4b7147bdf1a8.png)
