### ISSUE TITLE
Копирование текста

### ISSUE THREAD

**Issue by MireaStudentLoL** [SaltOnAStick/mistage-roadmap-game#2]
Нельзя копировать текст из области окна браузера. Копирование любого текста на страницах проекта возможно только из кода страницы. 
![изображение](https://user-images.githubusercontent.com/91137274/134183090-9486b7d8-12e5-4d6f-bc22-4005ee633d70.png)

**Comment by Nebulorion** [comment]
Во-первых, сейчас принято на авторских статьях закрывать доступ для копирования, поэтому это и не проблема. Большинство подобных сайтов позволяют копировать текст из "просмотра кода", т.к. принято считать, что пользователь не станет ради копирования текста делать лишние действия .
Во-вторых, проблема будет решена после обновления скрипта подгрузки страниц client-side-include.js, т.к. ошибка вызвана тем, что контент страницы перекрывается слоями от навигационного меню:
https://github.com/SaltOnAStick/mistage-roadmap-game/issues/1
